// Renders one field from a plain descriptor: { id, type, label, help,
// options, placeholder }. Patterned on compensation-comparison's Field.jsx,
// trimmed of its states-specific option source since nothing here needs it.
// type is one of "text" | "number" | "int" | "money" | "percent" | "enum" | "bool".
//
// field.help, when present, renders as a small info affordance next to the
// label (HelpIcon below) rather than an always-visible paragraph: it opens a
// Tooltip on hover/focus/tap, and the control itself carries
// aria-describedby pointing at that tooltip's content. Reserve field.help
// for clarification a user can look up on demand; a warning or a constraint
// the user must not miss stays as visible text next to/below the field
// instead (that text lives outside this component, in whichever caller
// needs it).

import { useId } from "react";
import { parseNumeric } from "../format.js";
import { color, label as labelStyle, input as inputStyle } from "../theme.js";
import { Tooltip } from "../../shared/Tooltip.jsx";

/** Percent fields are stored as decimals but typed as whole percentages. */
function toDisplay(field, value) {
  if (value == null) return "";
  if (field.type === "percent") return String(Math.round(value * 10000) / 100);
  return String(value);
}

function fromDisplay(field, raw) {
  if (raw === "") return field.type === "text" ? "" : null;
  if (field.type === "text") return raw;
  const n = parseNumeric(raw);
  if (n == null) return null;
  if (field.type === "percent") return n / 100;
  if (field.type === "int") return Math.round(n);
  return n;
}

const helpIconStyle = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  width: 14,
  height: 14,
  marginLeft: 5,
  padding: 0,
  fontSize: 10,
  fontWeight: 700,
  fontFamily: "inherit",
  lineHeight: 1,
  color: color.muted,
  background: color.tint,
  border: `1px solid ${color.rule}`,
  borderRadius: "50%",
  cursor: "help",
};

/**
 * Small "i" affordance opening a Tooltip with `text`. `id` is generated by
 * the caller (Field below, or a hand-built label+control row elsewhere, e.g.
 * BatteryEditor's hardware fields) so the same id can be put on the actual
 * input's aria-describedby -- HelpIcon has no reference to that input
 * itself, so it cannot wire that attribute on its own.
 */
export function HelpIcon({ id, text }) {
  return (
    <Tooltip id={id} content={text}>
      <button type="button" aria-label="More information" style={helpIconStyle}>
        i
      </button>
    </Tooltip>
  );
}

export function Field({ field, value, onChange, compact = false, idPrefix }) {
  // field.id names the descriptor, not a DOM node -- the same descriptor
  // (e.g. CostsEditor's OANDM_FIELD) renders once per config card, so a
  // fixed `f-${field.id}` id collides across cards and mis-targets every
  // <label for> after the first. idPrefix lets a caller with a natural
  // per-instance key (a config id, an array index) supply one; useId()
  // covers every other call site with a React-guaranteed-unique id.
  const autoId = useId();
  const id = `${idPrefix || autoId}-${field.id}`;
  const helpId = field.help ? `${id}-help` : undefined;

  let control;

  if (field.type === "bool") {
    // HelpIcon sits outside this <label>, as a sibling below, rather than
    // nested inside it: a click anywhere within a <label> wrapping a
    // checkbox also toggles that checkbox by default, so a help icon
    // nested in here would flip the field's value every time it was
    // clicked to open its tooltip.
    control = (
      <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12.5, color: color.body }}>
        <input
          id={id}
          type="checkbox"
          checked={!!value}
          onChange={(e) => onChange(e.target.checked)}
          aria-describedby={helpId}
          style={{ accentColor: color.accent }}
        />
        {field.label}
      </label>
    );
  } else if (field.type === "enum") {
    const options = field.options || [];
    control = (
      <select
        id={id}
        // Option values are strings in the DOM, so a numeric or null field
        // value has to be matched back against the option list by string form.
        value={value == null ? "" : String(value)}
        onChange={(e) => {
          const raw = e.target.value;
          const match = options.find((o) => String(o.value) === raw);
          onChange(match ? match.value : raw);
        }}
        aria-describedby={helpId}
        style={{ ...inputStyle, appearance: "auto" }}
      >
        {field.placeholder !== false && <option value="">Select…</option>}
        {options.map((o) => (
          <option key={String(o.value)} value={String(o.value)}>
            {o.label}
          </option>
        ))}
      </select>
    );
  } else {
    control = (
      <div style={{ position: "relative" }}>
        {field.type === "money" && (
          <span
            aria-hidden="true"
            style={{ position: "absolute", left: 8, top: "50%", transform: "translateY(-50%)", fontSize: 12.5, color: color.faint }}
          >
            $
          </span>
        )}
        <input
          id={id}
          type="text"
          inputMode={field.type === "text" ? "text" : "decimal"}
          value={toDisplay(field, value)}
          placeholder={field.placeholder || ""}
          onChange={(e) => onChange(fromDisplay(field, e.target.value))}
          aria-describedby={helpId}
          style={{
            ...inputStyle,
            paddingLeft: field.type === "money" ? 18 : undefined,
            paddingRight: field.type === "percent" ? 22 : undefined,
          }}
        />
        {field.type === "percent" && (
          <span
            aria-hidden="true"
            style={{ position: "absolute", right: 8, top: "50%", transform: "translateY(-50%)", fontSize: 12.5, color: color.faint }}
          >
            %
          </span>
        )}
      </div>
    );
  }

  // In both branches, HelpIcon is a sibling of the <label>, never nested
  // inside it: a click anywhere within a <label> also focuses/activates (or,
  // for a checkbox, toggles) its associated control, so a help icon nested
  // in here would fire that side effect every time it was clicked to open
  // its own tooltip instead.
  if (field.type === "bool") {
    return (
      <div style={{ marginBottom: compact ? 8 : 11, display: "flex", alignItems: "center" }}>
        {control}
        {field.help && <HelpIcon id={helpId} text={field.help} />}
      </div>
    );
  }

  return (
    <div style={{ marginBottom: compact ? 8 : 11 }}>
      <div style={{ display: "flex", alignItems: "center" }}>
        <label htmlFor={id} style={labelStyle}>
          {field.label}
        </label>
        {field.help && <HelpIcon id={helpId} text={field.help} />}
      </div>
      {control}
    </div>
  );
}
